# Generated by Django 4.2.5 on 2023-09-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("type", models.IntegerField(max_length=1)),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tracker.wallet")),
            ],
        ),
    ]
