# Generated by Django 4.2.5 on 2023-10-03 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_wallet_balance_in_uah"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="balance_in_uah",
        ),
    ]
